# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Final-Proj-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'


      - name: Restore NuGet packages (with retry)
        shell: pwsh
        run: |
          for ($i = 1; $i -le 3; $i++) {
            Write-Host "Attempt $i to restore packages..."
            try {
              dotnet restore ./Final_Project_Backend/Final_Project_WebAPI/Final_Project_WebAPI.csproj
              if ($LASTEXITCODE -eq 0) { break }
            } catch {
              Write-Host "Restore failed, retrying..."
              Start-Sleep -Seconds 10
            }
          }

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5986AF1FA81D4CE9A14C4880219AA3B5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C44E9C0FB3724408870EF45FA8317708 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1A81754D9DF343F1A28A94212C22C702 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Final-Proj-backend'
          slot-name: 'Production'
          package: .
          
